name: workflow overview


on:
  workflow_dispatch:
  push:
    branches: main_branch
    
jobs:
  my_selfhosted_job:
    name: my self hosted job
    runs-on: self-hosted
    steps:
    - name: step in a self-hosted runner
      id: selfhostedId
      shell: cmd
      run: |
        echo this is a multiline comment
        echo and this has been executed from my self-hosted runner
  a_simple_job:
    name: My simple job name
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is the first step from the first job"
      - name: step with another shell
        id: shellStep
        shell: python
        run: print("this step is using the python shell")
        
